# Site settings
title: Sachin Maheshwari
email: sachin.maheshwari8@gmail.com
description: ""
baseurl: ""
url: "http://yourdomain.com"
github_username:  sachinmaheshwari
linkedin_username: sachinmaheshwari1
disqus: sachin-blog

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

theme: jekyll-theme-cayman