# Site settings
title: Sachin Maheshwari
email: sachin.maheshwari8@hotmail.com
description: ""
baseurl: ""
url: "http://www.sachinm.com"
github_username:  sachinmaheshwari
linkedin_username: sachinmaheshwari1
disqus: sachin-blog
google_tag_id: UA-109385541-1

# Build settings
markdown: kramdown
permalink: /:title 
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
